### PR TITLE
Switch to new style exception messages

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
Fixes deprecation warning and improves py3k compatibility

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
Only question I have is whether we need a `if not None` guard or whether we can assume that we raise the exception with a value (e.g. as in http://stackoverflow.com/questions/13063212/deprecationwarning-baseexception-message-has-been-deprecated-as-of-python-2-6-e)

**Comment by kyleabeauchamp** [comment]
Looking closer, I think the constructor for RemoteError requires having a message present, so there's no need to guard against `None` in this case.

**Comment by jtratner** [comment]
Good catch! :)

Question: why not just use "str(exc)" here? My usual go to is just "%s: %s"
% type(exc).__name__, str(exc)

That to me is the idiomatic way of handling and avoids knowing about
implementation of the exception. (And I believe it covers same purpose here)

**Comment by kyleabeauchamp** [comment]
Done.  Agree that it's more idiomatic, I didn't realize that str/repr already had the correct logic written.

**Comment by jtratner** [comment]
Do you want to merge this?

**Comment by kyleabeauchamp** [comment]
+1 to merge

**Comment by jtratner** [comment]
(didn't realize you couldn't merge it yourself)

**Pull request merged**
